version: "3"
services:
  db:
    image: junghoonkim/database:latest
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    
    networks:
      - lolstagram
  
      
  frontend:
    image: junghoonkim/frontend:latest
    container_name: frontend
    ports:
      - 3000:80
    depends_on:
      - backend
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8080
    networks:
      - lolstagram

  backend:
    image: junghoonkim/backend:latest
    container_name: backend
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}


    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - lolstagram 

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - lolstagram
networks:
  lolstagram:
    driver: bridge