spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${dbUrl}
    username: admin
    password: ${dbPassword}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
    defer-datasource-initialization: true
    database-platform=org.hibernate.dialect: MySQL5InnoDBDialect
  sql:
    init:
      mode: always
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google_oatuh2_id}
            client-secret: ${google_oauth2_secret}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile
  data:
    redis:
      #      host: localhost
      host: 13.209.87.43
      port: 6379
      # 로컬에서는 비밀번호 필요 없음
      password: ${redisPassword}
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/


springdoc:
  swagger-ui:
    path: /api-docs.html
  api-docs:
    path: /api-docs
  show-actuator: true
  default-produces-media-type: application/json

jwt:
  accessKey: ${jwtAccessKey}
  refreshKey: ${jwtRefreshKey}

cloud:
  aws:
    credentials:
      access-key: ${awsAccessKey}
      secret-key: ${awsSecretKey}
    s3: #버킷이름
      bucket: pmm-s3-1
    region: #S3 지역
      static: ap-northeast-2
    stack:
      auto: false