name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - backend # frontend 브랜치에서의 push를 감지
    paths:
      - 'backend/**'
  pull_request:
    types:
      - closed # PR이 닫힐 때 (병합 포함)
    branches:
      - master # 대상 브랜치가 master일 때

jobs:
  run-on-merge:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true &&
        github.event.pull_request.base.ref == 'master' &&
        github.event.pull_request.head.ref == 'backend'

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Docker Buildx 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Docker 로그인 (Docker Hub 또는 Private Registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker Image
        run: |
          docker build -t junghoonkim/backend:latest ./backend
          docker push junghoonkim/backend:latest

      # 5. 배포 서버에 SSH로 접속하여 최신 Docker 이미지 배포
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{secrets.AWS_EC2_HOST}}
          username: ${{secrets.AWS_EC2_USERNAME}}
          key: ${{secrets.AWS_EC2_KEY}}
          script: |
            docker compose pull backend
            docker compose down backend || true  # backend 컨테이너 중지 및 삭제
            docker compose up -d backend
